### ISSUE TITLE
ShiftIt should preserve the (relative) locations of windows when switching screens...

### ISSUE THREAD

**Issue by onsi** [onsi/ShiftIt#1]

**Comment by drsharp** [comment]
Woo hoo! Let me know if you need a beta tester. I'd be happy to help with this feature in that regard.

**Comment by drsharp** [comment]
Any progress on this? (not to be pushy but I'd love this feature if you can make it happen)

**Comment by onsi** [comment]
:) give it a shot @drsharp

**Comment by drsharp** [comment]
Onsi,

That's awesome work! Thanks!
(by the way, it works very well, at least after 1 day of trying it out)

**Comment by onsi** [comment]
great!  glad you like, and sorry it took me 3 months to get to it!!!
