### ISSUE TITLE
Shiftit closes (or appears to) when dismissing preferences

### ISSUE THREAD

**Issue by Zteve** [onsi/ShiftIt#2]
I have shiftit in the menu bar and I click on it to get preferences. When I dismiss the preferences pane (red button, only way to do it) the application closes (and is removed from the menu bar).

This is possibly due to the fact that I have [RedQuits v2](http://www.macupdate.com/app/mac/39814/redquits) installed as well; but ShiftIt app shouldn't close when dismissing the preferences pane in any case.

**Comment by Zteve** [comment]
When RedQuits is removed, all is well. I will use this workaround in future.

**Comment by onsi** [comment]
Glad to hear that was the fix.  I think this is outside of ShiftIt's control?
